cmake_minimum_required(VERSION 3.16)
project(FMS)

set(FETCHCONTENT_BASE_DIR "${CMAKE_SOURCE_DIR}/External")

if(CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
    set(CMAKE_INSTALL_PREFIX "${CMAKE_SOURCE_DIR}/dist" CACHE PATH "..." FORCE)
endif()

# 하위 폴더 추가 (여기서 FMS 타겟이 생성됨)
add_subdirectory(FMS)

set_property(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} PROPERTY VS_STARTUP_PROJECT FMS)

install(
    TARGETS TLogger
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
)